apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-model-pvc
  namespace: kc-ai-research-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-igrok
  resources:
    requests:
      storage: 200Gi
